import { PaperSize, MediaType, PrinterProfile } from '../types/print';

export const PAPER_SIZES: PaperSize[] = [
  // Standar Lembar Terpopuler
  {
    id: 'a4',
    name: 'A4',
    widthMm: 210,
    heightMm: 297,
    category: 'standard',
    description: 'Standar kantor & dokumen internasional (210 × 297 mm)',
    isPopular: true,
  },
  {
    id: 'f4',
    name: 'F4 / Folio (Indonesia)',
    widthMm: 215.9,
    heightMm: 330.2,
    category: 'standard',
    description: 'Standar map, formulir dinas & HVS Folio di Indonesia (21,5 × 33 cm)',
    isPopular: true,
  },
  {
    id: 'letter',
    name: 'Letter (US)',
    widthMm: 215.9,
    heightMm: 279.4,
    category: 'standard',
    description: 'Standar Amerika Utara (8,5 × 11 inchi / 215,9 × 279,4 mm)',
  },
  {
    id: 'legal',
    name: 'Legal (US)',
    widthMm: 215.9,
    heightMm: 355.6,
    category: 'standard',
    description: 'Standar Legal US (8,5 × 14 inchi) — Lebih panjang dari F4!',
  },
  {
    id: 'a5',
    name: 'A5',
    widthMm: 148,
    heightMm: 210,
    category: 'standard',
    description: 'Setengah A4, untuk buku saku, brosur, nota (148 × 210 mm)',
    isPopular: true,
  },
  {
    id: 'a6',
    name: 'A6',
    widthMm: 105,
    heightMm: 148,
    category: 'standard',
    description: 'Seperempat A4, untuk kartu pos & undangan (105 × 148 mm)',
  },
  {
    id: 'a3',
    name: 'A3',
    widthMm: 297,
    heightMm: 420,
    category: 'standard',
    description: 'Dua kali A4 (297 × 420 mm) — Butuh printer A3 (misal Epson L1300/L1800)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'a3_plus',
    name: 'A3+ (Super A3)',
    widthMm: 329,
    heightMm: 483,
    category: 'standard',
    description: '329 × 483 mm untuk poster proofing & percetakan',
    requiresSpecialPrinter: true,
  },
  {
    id: 'executive',
    name: 'Executive',
    widthMm: 184.15,
    heightMm: 266.7,
    category: 'standard',
    description: '184,15 × 266,7 mm',
  },
  {
    id: 'b5',
    name: 'B5 (JIS)',
    widthMm: 176,
    heightMm: 250,
    category: 'standard',
    description: 'Ukuran buku agenda, novel, dan modul pelajaran (176 × 250 mm)',
    isPopular: true,
  },
  {
    id: 'b4',
    name: 'B4',
    widthMm: 250,
    heightMm: 353,
    category: 'standard',
    description: '250 × 353 mm — Format antara A4 dan A3',
  },
  {
    id: 'sra3',
    name: 'SRA3',
    widthMm: 320,
    heightMm: 450,
    category: 'extended',
    description: 'Raw format percetakan digital offset (320 × 450 mm)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'sra4',
    name: 'SRA4',
    widthMm: 225,
    heightMm: 320,
    category: 'extended',
    description: '225 × 320 mm',
  },

  // Foto
  {
    id: 'photo_2r',
    name: 'Foto 2R (Wallet / Dompet)',
    widthMm: 60,
    heightMm: 90,
    category: 'photo',
    description: 'Foto mini ukuran dompet (60 × 90 mm)',
  },
  {
    id: 'photo_3r',
    name: 'Foto 3R (8,9 × 12,7 cm)',
    widthMm: 89,
    heightMm: 127,
    category: 'photo',
    description: 'Ukuran album foto klasik 3R (89 × 127 mm)',
    isPopular: true,
  },
  {
    id: 'photo_4r',
    name: 'Foto 4R (10 × 15 cm)',
    widthMm: 102,
    heightMm: 152,
    category: 'photo',
    description: 'Ukuran cetak foto standar 4R terpopuler (102 × 152 mm)',
    isPopular: true,
  },
  {
    id: 'photo_5r',
    name: 'Foto 5R (13 × 18 cm)',
    widthMm: 127,
    heightMm: 178,
    category: 'photo',
    description: 'Ukuran foto bingkai meja 5R (127 × 178 mm)',
    isPopular: true,
  },
  {
    id: 'photo_8r',
    name: 'Foto 8R (20 × 25 cm)',
    widthMm: 203,
    heightMm: 254,
    category: 'photo',
    description: 'Ukuran foto bingkai dinding 8R (203 × 254 mm)',
    isPopular: true,
  },
  {
    id: 'photo_10r',
    name: 'Foto 10R (25 × 30 cm)',
    widthMm: 254,
    heightMm: 305,
    category: 'photo',
    description: 'Ukuran foto wisuda / potret besar 10R (254 × 305 mm)',
  },
  {
    id: 'photo_2x3',
    name: 'Pas Foto 2 × 3 cm',
    widthMm: 20,
    heightMm: 30,
    category: 'photo',
    description: 'Standar pas foto kartu pelajar & buku nikah (20 × 30 mm)',
  },
  {
    id: 'photo_3x4',
    name: 'Pas Foto 3 × 4 cm',
    widthMm: 28,
    heightMm: 38,
    category: 'photo',
    description: 'Standar berkas lamaran & ijazah Indonesia (28 × 38 mm)',
    isPopular: true,
  },
  {
    id: 'photo_4x6',
    name: 'Pas Foto 4 × 6 cm',
    widthMm: 38,
    heightMm: 56,
    category: 'photo',
    description: 'Standar paspor & dokumen resmi Indonesia (38 × 56 mm)',
    isPopular: true,
  },

  // Amplop & Kartu ID
  {
    id: 'id_card',
    name: 'Kartu ID / KTP (CR80)',
    widthMm: 85.6,
    heightMm: 53.98,
    category: 'standard',
    description: 'Ukuran standar KTP, SIM, ATM, dan kartu member (85,6 × 54 mm)',
    isPopular: true,
  },
  {
    id: 'envelope_dl',
    name: 'Amplop DL (11 × 22 cm)',
    widthMm: 110,
    heightMm: 220,
    category: 'standard',
    description: 'Amplop surat dinas panjang / bisnis (110 × 220 mm)',
  },
  {
    id: 'envelope_c5',
    name: 'Amplop C5 (16,2 × 22,9 cm)',
    widthMm: 162,
    heightMm: 229,
    category: 'standard',
    description: 'Amplop untuk kertas A5 atau A4 lipat dua (162 × 229 mm)',
  },
  {
    id: 'envelope_c6',
    name: 'Amplop C6 (11,4 × 16,2 cm)',
    widthMm: 114,
    heightMm: 162,
    category: 'standard',
    description: 'Amplop kartu undangan kecil (114 × 162 mm)',
  },

  // Large Format / Plotter (khusus persiapan file)
  {
    id: 'a2',
    name: 'A2 (Plotter/Arsitektur)',
    widthMm: 420,
    heightMm: 594,
    category: 'extended',
    description: '420 × 594 mm — Khusus plotter besar',
    requiresSpecialPrinter: true,
  },
  {
    id: 'a1',
    name: 'A1 (Plotter/Cetak Biru)',
    widthMm: 594,
    heightMm: 841,
    category: 'extended',
    description: '594 × 841 mm — Khusus plotter besar',
    requiresSpecialPrinter: true,
  },
  {
    id: 'a0',
    name: 'A0 (Banner/Plotter Arsitektur)',
    widthMm: 841,
    heightMm: 1189,
    category: 'extended',
    description: '841 × 1189 mm — Khusus plotter besar',
    requiresSpecialPrinter: true,
  },

  // Kategori Khusus: Roll & Continuous Form
  {
    id: 'thermal_58',
    name: 'Thermal Roll 58 mm',
    widthMm: 58,
    heightMm: 100, // dinamis
    category: 'specialized_roll',
    description: 'Struk kasir mini thermal (Lebar 58 mm, tinggi dinamis)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'thermal_80',
    name: 'Thermal Roll 80 mm',
    widthMm: 80,
    heightMm: 150,
    category: 'specialized_roll',
    description: 'Struk restoran/POS thermal (Lebar 80 mm)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'continuous_95x11',
    name: 'Continuous Form 9.5 × 11 inchi',
    widthMm: 241.3,
    heightMm: 279.4,
    category: 'specialized_roll',
    description: 'Kertas komputer berlubang pinggir (Dot Matrix seperti Epson LX-310)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'continuous_95x12',
    name: 'Continuous Form 9.5 × 12 inchi',
    widthMm: 241.3,
    heightMm: 304.8,
    category: 'specialized_roll',
    description: 'Kertas perforasi faktur / surat jalan (Dot Matrix)',
    requiresSpecialPrinter: true,
  },
  {
    id: 'custom',
    name: 'Ukuran Kustom (Custom mm)',
    widthMm: 210,
    heightMm: 297,
    category: 'standard',
    description: 'Tentukan lebar dan tinggi sendiri dalam milimeter',
  },
];

export const MEDIA_TYPES: MediaType[] = [
  {
    id: 'hvs',
    name: 'HVS Putih (Woodfree / Bond)',
    category: 'standard',
    availableGsm: [70, 75, 80, 100],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper / Bright White Paper',
    description: 'Kertas fotokopi & cetak sehari-hari, cepat menyerap tinta.',
  },
  {
    id: 'hvs_color',
    name: 'HVS Warna (Pastel / Rainbow)',
    category: 'standard',
    availableGsm: [70, 80],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper',
    description: 'Kertas HVS dengan warna dasar lembut untuk selebaran & brosur.',
  },
  {
    id: 'photo_glossy',
    name: 'Photo Paper Glossy',
    category: 'photo',
    availableGsm: [180, 200, 230, 260],
    recommendedDpi: 300,
    epsonPaperType: 'Epson Premium Glossy / Photo Paper Glossy',
    description: 'Permukaan mengkilap dengan kontras tajam untuk cetak foto.',
  },
  {
    id: 'photo_matte',
    name: 'Matte Paper / Inkjet Paper',
    category: 'photo',
    availableGsm: [120, 150, 220],
    recommendedDpi: 300,
    epsonPaperType: 'Epson Matte',
    description: 'Permukaan doff halus tanpa pantulan cahaya, tajam untuk infografis.',
  },
  {
    id: 'art_paper',
    name: 'Art Paper',
    category: 'standard',
    availableGsm: [100, 120, 150],
    recommendedDpi: 300,
    epsonPaperType: 'Epson Matte / Photo Paper',
    description: 'Kertas licin semi-glossy tipis untuk brosur dan flyer percetakan.',
  },
  {
    id: 'art_carton',
    name: 'Art Carton',
    category: 'card',
    availableGsm: [190, 210, 230, 260, 310, 350],
    recommendedDpi: 300,
    epsonPaperType: 'Epson Matte / Ultra Glossy',
    description: 'Kertas tebal kaku untuk cover buku, kartu nama, kemasan, poster.',
  },
  {
    id: 'buffalo',
    name: 'Buffalo / Brief Card (BC)',
    category: 'card',
    availableGsm: [150, 160, 220],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper / Thick Paper',
    description: 'Kertas berserat agak kasar biasa untuk jilid makalah dan sertifikat.',
  },
  {
    id: 'concorde',
    name: 'Concorde (Tekstur Serat Lembut)',
    category: 'specialty',
    availableGsm: [90, 120, 220],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper / Matte',
    description: 'Kertas bertekstur lekukan lembut mewah untuk kop surat dan sertifikat.',
  },
  {
    id: 'linen',
    name: 'Linen Jepang (Tekstur Garis Silang)',
    category: 'specialty',
    availableGsm: [200, 230],
    recommendedDpi: 300,
    epsonPaperType: 'Matte / Thick Paper',
    description: 'Tekstur anyaman kain halus premium untuk kartu nama dan sertifikat.',
  },
  {
    id: 'jasmine',
    name: 'Jasmine (Glitter Mutiara)',
    category: 'specialty',
    availableGsm: [210],
    recommendedDpi: 300,
    epsonPaperType: 'Matte',
    description: 'Kertas berkelap-kelip efek mutiara untuk kartu undangan pernikahan.',
  },
  {
    id: 'sticker_chromo',
    name: 'Sticker Kertas Chromo / Bontax',
    category: 'sticker',
    availableGsm: [140],
    recommendedDpi: 300,
    epsonPaperType: 'Photo Paper Glossy',
    description: 'Stiker kertas berperekat mengkilap ekonomis untuk label kemasan.',
  },
  {
    id: 'sticker_vinyl',
    name: 'Sticker Vinyl (Waterproof Inkjet)',
    category: 'sticker',
    availableGsm: [150],
    recommendedDpi: 300,
    epsonPaperType: 'Epson Premium Glossy',
    description: 'Stiker bahan sintetis lentur tahan air untuk outdoor.',
  },
  {
    id: 'sticker_transparan',
    name: 'Sticker Transparan',
    category: 'sticker',
    availableGsm: [130],
    recommendedDpi: 300,
    epsonPaperType: 'Photo Paper Glossy',
    description: 'Stiker bening tembus pandang untuk botol kaca/plastik.',
  },
  {
    id: 'sticker_kraft',
    name: 'Sticker Kraft Coklat',
    category: 'sticker',
    availableGsm: [120],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper',
    description: 'Stiker kertas coklat bernuansa retro / ramah lingkungan.',
  },
  {
    id: 'kalkir',
    name: 'Kalkir / Tracing Paper',
    category: 'specialty',
    availableGsm: [80, 100],
    recommendedDpi: 300,
    epsonPaperType: 'Plain Paper',
    description: 'Kertas semi-transparan untuk gambar teknik dan cetak film sablon.',
  },
];

export const PRINTER_PROFILES: PrinterProfile[] = [
  {
    id: 'epson_l3110',
    name: 'Epson EcoTank L3110 / L3210 (Default)',
    maxPaperWidthMm: 215.9, // 8.5 inchi (A4, F4, Legal)
    supportedPaperIds: ['a4', 'f4', 'letter', 'legal', 'a5', 'a6', 'photo_4r', 'photo_5r', 'photo_3x4', 'photo_4x6', 'custom'],
    supportsBorderless: true, // borderless hingga 4R
    notes: 'Mendukung hingga lebar 215,9 mm. Untuk kertas F4/Folio, pilih ukuran User-Defined (215.9 × 330.2 mm) pada driver jika opsi F4 belum terdaftar.',
  },
  {
    id: 'generic_inkjet_a4',
    name: 'Printer Inkjet Standar A4 / F4 (Canon, HP, Brother)',
    maxPaperWidthMm: 215.9,
    supportedPaperIds: ['a4', 'f4', 'letter', 'legal', 'a5', 'a6', 'photo_4r', 'photo_5r', 'photo_3x4', 'photo_4x6', 'custom'],
    supportsBorderless: true,
    notes: 'Kompatibel dengan sebagian besar printer rumahan/kantor kelas A4/F4.',
  },
  {
    id: 'inkjet_a3',
    name: 'Printer A3 / A3+ (Epson L1300, L1800, dll)',
    maxPaperWidthMm: 329,
    supportedPaperIds: ['a4', 'f4', 'letter', 'legal', 'a5', 'a6', 'a3', 'a3_plus', 'photo_4r', 'photo_5r', 'custom'],
    supportsBorderless: true,
    notes: 'Dapat mencetak kertas format besar hingga ukuran A3+ (329 × 483 mm).',
  },
  {
    id: 'specialized_devices',
    name: 'Printer Khusus / Non-Lembar (Thermal / Dot Matrix / Plotter)',
    maxPaperWidthMm: 1200,
    supportedPaperIds: ['a2', 'a1', 'a0', 'thermal_58', 'thermal_80', 'continuous_95x11', 'continuous_95x12'],
    supportsBorderless: false,
    notes: 'Perangkat khusus kasir POS, mesin dot matrix invoice, atau plotter arsitektur.',
  },
];

export const MARGIN_PRESETS: { [key: string]: { name: string; top: number; bottom: number; left: number; right: number; desc: string } } = {
  borderless: {
    name: 'Nol / Borderless (0 mm)',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    desc: 'Gambar memenuhi ujung kertas tanpa tepi putih.',
  },
  safe_inkjet: {
    name: 'Standar Aman Inkjet (3.5 mm)',
    top: 3.5,
    bottom: 3.5,
    left: 3.5,
    right: 3.5,
    desc: 'Batas hardware fisik printer non-borderless agar tidak terpotong.',
  },
  standard_doc: {
    name: 'Standar Dokumen (10 mm / 1 cm)',
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
    desc: 'Rapi dan proporsional untuk dokumen kantor & materi cetak umum.',
  },
  binding_thesis: {
    name: 'Jilid / Skripsi (Kiri 20 mm, lainnya 10 mm)',
    top: 10,
    bottom: 10,
    left: 20,
    right: 10,
    desc: 'Memberikan ruang ekstra di sebelah kiri untuk staples atau jilid spiral.',
  },
};
